// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNP-TXmLWTPXRIIzxF8jKy2qYsy21F60g',
    appId: '1:474203552700:web:801c8b4ccc4b98c8be89b9',
    messagingSenderId: '474203552700',
    projectId: 'smartfleet-pro-dev',
    authDomain: 'smartfleet-pro-dev.firebaseapp.com',
    storageBucket: 'smartfleet-pro-dev.firebasestorage.app',
    measurementId: 'G-B6K6MDHP70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTIiuSvGHEFDzxPAk5Rc9gqQYbJsB5gMw',
    appId: '1:474203552700:android:8220bdbd6e23a3abbe89b9',
    messagingSenderId: '474203552700',
    projectId: 'smartfleet-pro-dev',
    storageBucket: 'smartfleet-pro-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwo07meVr9vnzIPmmCd4HO6iep9UPDeYo',
    appId: '1:474203552700:ios:ff290985ab2230c4be89b9',
    messagingSenderId: '474203552700',
    projectId: 'smartfleet-pro-dev',
    storageBucket: 'smartfleet-pro-dev.firebasestorage.app',
    iosClientId: '474203552700-rf1h7uh2cp03pmuredqcqefi88f3kq5c.apps.googleusercontent.com',
    iosBundleId: 'com.hilde.smartfleetpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwo07meVr9vnzIPmmCd4HO6iep9UPDeYo',
    appId: '1:474203552700:ios:ff290985ab2230c4be89b9',
    messagingSenderId: '474203552700',
    projectId: 'smartfleet-pro-dev',
    storageBucket: 'smartfleet-pro-dev.firebasestorage.app',
    iosClientId: '474203552700-rf1h7uh2cp03pmuredqcqefi88f3kq5c.apps.googleusercontent.com',
    iosBundleId: 'com.hilde.smartfleetpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNP-TXmLWTPXRIIzxF8jKy2qYsy21F60g',
    appId: '1:474203552700:web:870fa1c31e671644be89b9',
    messagingSenderId: '474203552700',
    projectId: 'smartfleet-pro-dev',
    authDomain: 'smartfleet-pro-dev.firebaseapp.com',
    storageBucket: 'smartfleet-pro-dev.firebasestorage.app',
    measurementId: 'G-HRJDWYCVQ2',
  );
}
